### ISSUE TITLE
Problem while running certain turbines model

### ISSUE THREAD

**Issue by AsimUdel** [NREL/openfast-turbine-models#10]
Hello All,
I want to ask you something what I am facing, I am using AMR-Wind for wind farm modeling and for turbine modeling I am using (FastDisk, actuator method) using OpenFAST. I am able to use to use certain turbine models by NREL (1.7MW and 2.5MW) but right now I could not use (3.4 (https://github.com/IEAWindTask37/IEA-3.4-130-RWT)) or 10 MW (https://github.com/IEAWindTask37/IEA-10.0-198-RWT)). I am using AMR-Wind (v1.0), OpenFAST(v3.1) and ROSCO (v2.9), and have modified (OpenFAST files to version 3.1) of all turbine models (following (https://github.com/lawrenceccheung/amrwind-frontend/blob/afbc1dd284095ee869ba8a9cd3760fdf8b08ca82/docs/openfast_turbine.md#going-from-openfast-v26-to-v300) but still was not successful in running simulation. I cannot attach the the zip files of (NREL 2.5, 3.4 and 10 MW turbines) but I will give the link from where I am downloading the OpenFAST files. Kindly someone take a look and help me in this matter. 
NREL 2.5 : https://github.com/NREL/openfast-turbine-models/tree/main/IEA-scaled/legacy_models/NREL-2.5-116
NREL 10: https://github.com/IEAWindTask37/IEA-10.0-198-RWT
NREL 3.4: https://github.com/IEAWindTask37/IEA-3.4-130-RWT
[2.5MW_output.txt](https://github.com/NREL/openfast-turbine-models/files/15225543/2.5MW_output.txt)
[3.4MW_output.txt](https://github.com/NREL/openfast-turbine-models/files/15225544/3.4MW_output.txt)
[10MW_output.txt](https://github.com/NREL/openfast-turbine-models/files/15225545/10MW_output.txt)
P.S. 2.5 MW runs after warning but not others.

Thanks 
Asim

**Comment by ewquon** [comment]
Hi Asim, sorry this slipped through the cracks, I was out of the office on leave. I'm not supporting the development of the 3.4 and 10 MW IEA RWTs. Also, I hope you are aware that we have new versions of the NREL open-source turbine models that should be used instead of the legacy models. From looking at one of your output files, it just seems like you have a mismatch in openfast versions and need to update your input files to have all the right input parameters on the right lines. Hopefully you figured this out already.
